server:
  servlet:
    context-path: /yis-api
  port: 8888

spring:
  application:
    name: springboot3-jdk17-dev
  datasource:
    url: jdbc:mysql://cs.nes.com.cn:3308/demo?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ctcetest
    password: NES@ctceZO1B3
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 8.146.210.225
      port: 6379
      password: Cjsj#36zs
      timeout: 3000 # 读取超时时间（毫秒）
      connect-timeout: 5000 # 连接超时时间（毫秒）
      database: 15 #默认数据库
      jedis:
        pool:
          max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 5 # 连接池中的最小空闲连接


# 配置mybatis-plus
mybatis-plus:
  # 配置mapper.xml文件的路径
  mapper-locations: classpath*:/mapper/*.xml
  # 配置实体类的路径
  type-aliases-package: cn.com.yis.domain
  # 开启驼峰命名映射
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 日志相关配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: log/
  level:
    root: INFO
    cn.com.yis.mapper: debug



user:
  name: yishuai
  #  age: 11
  age: ${random.int(10)}
  phone: 13800000000
  email: yishuai@example.com
  address:
    areaCode: 11
    city: 北京
    description: ${user.name}家在${user.address.city}
