server:
  servlet:
    context-path: /yis-api
  port: 8888

spring:
  application:
    name: springboot3-jdk17
  config:
    import:
      - optional:nacos:springboot3-jdk17
  cloud:
    nacos:
      server-addr: 8.152.208.41:8848
      config:
        group: TEST
        refresh-enabled: true
        server-addr: ${spring.cloud.nacos.server-addr}
        file-extension: yaml
